# Basic Information 
title: Lujing 
position: Ph.D. Student
affiliation: University of Texas at Dallas
subaffiliation: Erik Jonsson School of Engineering and Computer Science
affiliation_link: https://www.utdallas.edu/
subaffiliation_link: https://engineering.utdallas.edu/
# affiliation_logo: ./assets/img/hkust.jpeg
email: lujing.xie (at) UTDallas.edu
# email2: song.chen (at) universite-paris-saclay.fr
address: About To Move
# address_link: https://www.google.fr/maps/place/Spin-Ion+Technologies/@48.7124352,2.194429,17z/data=!3m2!4b1!5s0x47e678bdc29075f7:0xbce23cefe16f4791!4m6!3m5!1s0x47e678bdc3c95555:0xe09ceff0db3725ab!8m2!3d48.7124317!4d2.1970093!16s%2Fg%2F11r4m02q4g?entry=ttu

# Search Engine Optimization (SEO)
keywords: lujing xie, xie lujing, lujing, xie, lujing(xie)
canonical: https://minimal-light-theme.yliu.me/
description: Lujing Xie is a Ph.D. student in Computer Science at the University of Texas at Dallas. He earned his Bachelor's degree from the Department of Yuanpei College at Peking University in 2025. His research focuses on large language models and vision-language models.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
cv_link: https://drive.google.com/file/d/11irUmNNVVtlf6RVODLek3QEUnvuQQggu/view?usp=sharing
google_scholar: https://scholar.google.com/citations?user=7BP35m0AAAAJ&hl=zh-CN
github_link: https://github.com/lajiman
linkedin: https://www.linkedin.com/in/lujing-xie-440a43335/
# researchgate: https://www.researchgate.net/profile/Song-Chen-60

# Images 
avatar: ./assets/img/avatar3.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false
#footnote: Feel free to use my website's source code.
#footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: ${{ secrets.CLUSTRMAPS_ID }}

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: ${{ secrets.GOOGLE_SCHOLAR_ID }}

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one




# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME